<?php

namespace Dywee\OrderCMSBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * OrderStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatRepository extends EntityRepository
{
    public function getStats($type, $beginAt, $endAt, $detail = 'day')
    {
        $qb = $this->createQueryBuilder('s')
            ->select('count(s.id) as total, s.createdAt, SUBSTRING(s.createdAt, 0, 10) as dateForGroupBy, s.type')
            ->where('s.type = :type and s.createdAt between :beginAt and :endAt')
            ->setParameters(array(
                    'type' => $type,
                    'beginAt' => $beginAt,
                    'endAt' => $endAt)
            )
            ->orderBy('s.createdAt', 'asc');

        if($detail == 'day')
            $qb->groupBy('dateForGroupBy');

        return $qb->getQuery()->getResult();
    }
}
